// 制作者が独自に作成したCT-AI学習問題。公式問題・公式本文は使用しない。

export const questions = [
  {
    id: 'ct-ai-001',
    sectionRef: '1.1',
    sourcePolicy: 'original',
    officialQuestionUsed: false,
    certificationReference: 'JSTQB CT-AI syllabus v1.0 referenced only as topic map',
    loCode: 'AI-1.1',
    kLevel: 'K2',
    topic: 'AIの定義とAI効果',
    question: '物流会社が、過去の配送実績から翌日の遅延リスクを予測する機能を導入した。担当者が「高精度なので人間と同じ意味で理解している」と説明している。最も適切な捉え方はどれか。',
    choices: ['（A）予測精度が高ければ、人間と同じ理解を持つと判断できる', '（B）入力から有用な予測を生成していても、人間と同じ理解を持つとは限らない', '（C）過去データを使う機能はAIとは呼べない', '（D）人間が結果を確認する限り、AI効果は発生しない'],
    correctAnswerIndex: 1,
    explanation: 'AI効果とは、実現前には知的に見えた機能が普及後に単なる自動化と見なされやすい現象である。高い予測性能は業務価値を示すが、人間と同様の意味理解や意識を持つ証拠にはならない。機能と能力の範囲を分けて評価する必要がある。',
    reviewerStatus: 'reviewed',
  },
  {
    id: 'ct-ai-002',
    sectionRef: '1.3',
    sourcePolicy: 'original',
    officialQuestionUsed: false,
    certificationReference: 'JSTQB CT-AI syllabus v1.0 referenced only as topic map',
    loCode: 'AI-1.3',
    kLevel: 'K2',
    topic: 'AIベースのシステムと従来のシステム',
    question: '銀行が、固定ルールで送金上限を判定する機能を、取引履歴から不正確率を推定するモデルへ置き換えた。テスト計画で新たに重視すべき点はどれか。',
    choices: ['（A）ソースコードの分岐網羅だけで期待品質を判断する', '（B）同じ入力には常に同じ出力が返ることだけを確認する', '（C）学習データの代表性と、確率出力に対する許容基準を確認する', '（D）画面の配置が旧機能と同じであることだけを確認する'],
    correctAnswerIndex: 2,
    explanation: '学習モデルの振る舞いは、明示した業務ルールだけでなく訓練データの分布や品質にも依存する。また出力が確率値なら、完全一致ではなく業務リスクに応じたしきい値や誤判定率を評価する必要がある。従来型の分岐確認だけでは不十分である。',
    reviewerStatus: 'reviewed',
  },
  {
    id: 'ct-ai-003',
    sectionRef: '1.7',
    sourcePolicy: 'original',
    officialQuestionUsed: false,
    certificationReference: 'JSTQB CT-AI syllabus v1.0 referenced only as topic map',
    loCode: 'AI-1.7',
    kLevel: 'K2',
    topic: 'AI as a Service（AIaaS）',
    question: '旅行会社が外部の画像認識サービスを使い、投稿写真から観光地を分類している。サービス提供者が予告なくモデルを更新できる場合、利用企業のテストとして最も重要な対応はどれか。',
    choices: ['（A）契約時に一度だけ精度を確認し、その後の確認を省く', '（B）提供者の内部コードを必ず入手して全行を確認する', '（C）応答速度だけを継続監視し、分類結果は監視しない', '（D）代表的な固定データで定期的に再評価し、変更時の性能低下を検出する'],
    correctAnswerIndex: 3,
    explanation: '外部サービスでは利用者がモデルや更新時期を直接管理できないことがある。そのため、代表的な回帰用データと期待する性能基準を保持し、定期実行や変更通知を契機に再評価する。精度、偏り、応答時間など利用側の品質特性を継続監視することが重要である。',
    reviewerStatus: 'reviewed',
  },
  {
    id: 'ct-ai-004',
    sectionRef: '1.8',
    sourcePolicy: 'original',
    officialQuestionUsed: false,
    certificationReference: 'JSTQB CT-AI syllabus v1.0 referenced only as topic map',
    loCode: 'AI-1.8',
    kLevel: 'K2',
    topic: '学習済みモデル',
    question: '製造会社が一般画像で学習済みのモデルを流用し、工場内の微細な傷を分類しようとしている。導入前の評価で最も適切な考慮事項はどれか。',
    choices: ['（A）元の学習目的と工場データの差を確認し、実データで再評価する', '（B）学習済みであるため、追加の評価や調整は不要とする', '（C）モデルのファイルサイズだけで傷の分類性能を判断する', '（D）元データの件数が多ければ、対象領域の違いを無視する'],
    correctAnswerIndex: 0,
    explanation: '学習済みモデルは開発を効率化できるが、元のデータ領域と利用先の画像条件が異なれば性能は保証されない。照明、材質、傷の大きさなどの差を分析し、現場を代表するデータで評価する。必要に応じて追加学習し、その後も独立したデータで確認する。',
    reviewerStatus: 'reviewed',
  },
  {
    id: 'ct-ai-005',
    sectionRef: '1.9',
    sourcePolicy: 'original',
    officialQuestionUsed: false,
    certificationReference: 'JSTQB CT-AI syllabus v1.0 referenced only as topic map',
    loCode: 'AI-1.9',
    kLevel: 'K2',
    topic: '規格・規制・AI',
    question: '医療支援モデルを複数地域で提供する計画がある。品質責任者が、開発開始時に規格や法的要求を確認する主な理由として最も適切なものはどれか。',
    choices: ['（A）モデルの精度を自動的に最大化できるため', '（B）地域や用途による記録、説明、リスク管理の要求を計画へ反映するため', '（C）すべてのテストを外部機関へ移管できるため', '（D）利用データの偏りが必ず解消されるため'],
    correctAnswerIndex: 1,
    explanation: '適用される要求は地域、用途、リスクの大きさによって異なり、データ管理、説明、監視、記録保存などに影響する。後工程で不足が判明すると設計変更が大きくなるため、対象市場と利用目的を早期に整理し、必要な証拠やテスト活動を計画へ組み込む。',
    reviewerStatus: 'reviewed',
  },
  {
    id: 'ct-ai-006',
    sectionRef: '2.4',
    sourcePolicy: 'original',
    officialQuestionUsed: false,
    certificationReference: 'JSTQB CT-AI syllabus v1.0 referenced only as topic map',
    loCode: 'AI-2.4',
    kLevel: 'K2',
    topic: 'バイアス',
    question: '採用支援モデルの全体正解率は高いが、特定の職種経験を持つ応募者だけ見送り率が著しく高い。チームが最初に行うべき調査はどれか。',
    choices: ['（A）全体正解率が高いため、そのまま公開する', '（B）対象群のデータを削除して差を見えなくする', '（C）群別の誤判定率と、訓練データの分布やラベル付与過程を調べる', '（D）モデル名を変更して再度同じ評価を行う'],
    correctAnswerIndex: 2,
    explanation: '全体指標は、人数の少ない群で生じる不利益を隠すことがある。対象群ごとの偽陽性率や偽陰性率を比較し、標本数、欠損、代理変数、過去判断を用いたラベルなどを確認する。原因を特定したうえで、データや特徴量、判断手順の改善を検討する。',
    reviewerStatus: 'reviewed',
  },
  {
    id: 'ct-ai-007',
    sectionRef: '2.5',
    sourcePolicy: 'original',
    officialQuestionUsed: false,
    certificationReference: 'JSTQB CT-AI syllabus v1.0 referenced only as topic map',
    loCode: 'AI-2.5',
    kLevel: 'K2',
    topic: '倫理',
    question: '保険会社が契約者の行動履歴から保険料を提案する機能を開発している。法務確認だけでは倫理面の検討が十分でない理由として最も適切なものはどれか。',
    choices: ['（A）法的に許されても、監視感や不公平な扱いなど利害関係者への害が残り得るため', '（B）倫理面を検討するとモデルの学習時間が必ず短くなるため', '（C）倫理は画面デザインだけに関係するため', '（D）法的要求と倫理的配慮は常に完全に一致するため'],
    correctAnswerIndex: 0,
    explanation: '法的に実施可能でも、本人の期待を超えたデータ利用、説明しにくい差別的影響、選択の自由の低下などが生じる場合がある。影響を受ける人を洗い出し、利益と害、同意、異議申立て、人による見直しを含めて設計判断を評価する必要がある。',
    reviewerStatus: 'reviewed',
  },
  {
    id: 'ct-ai-008',
    sectionRef: '2.7',
    sourcePolicy: 'original',
    officialQuestionUsed: false,
    certificationReference: 'JSTQB CT-AI syllabus v1.0 referenced only as topic map',
    loCode: 'AI-2.7',
    kLevel: 'K2',
    topic: '透明性・解釈可能性・説明可能性',
    question: '融資審査モデルについて、顧客対応部門は個別の否決理由を説明したい。一方、開発部門はモデル全体で重要な特徴量一覧だけを提示した。何が不足しているか。',
    choices: ['（A）モデルの学習に使った計算機の型番', '（B）全顧客を平均した処理時間の説明', '（C）ソースコードの行数に関する情報', '（D）個別の判断にどの入力がどのように影響したかを示す局所的な説明'],
    correctAnswerIndex: 3,
    explanation: '全体的な特徴量重要度はモデル傾向の理解には役立つが、特定顧客の否決理由を直接示すものではない。個別判断には局所的な説明が必要であり、その説明が元モデルの振る舞いを十分に近似しているか、利用者が誤解しない表現かも検証する必要がある。',
    reviewerStatus: 'reviewed',
  },
  {
    id: 'ct-ai-009',
    sectionRef: '3.2',
    sourcePolicy: 'original',
    officialQuestionUsed: false,
    certificationReference: 'JSTQB CT-AI syllabus v1.0 referenced only as topic map',
    loCode: 'AI-3.2',
    kLevel: 'K2',
    topic: 'MLワークフロー',
    question: '需要予測モデルの試作で良い結果が出たため、担当者は直ちに本番公開しようとしている。MLワークフロー上、公開前に特に必要な活動はどれか。',
    choices: ['（A）訓練データで最高得点だったことだけを記録する', '（B）独立したデータで評価し、配備後の監視と更新方法を定める', '（C）特徴量を増やせるだけ増やし、再評価を省略する', '（D）モデルの出力をすべて手作業の固定値へ置き換える'],
    correctAnswerIndex: 1,
    explanation: '試作時の結果だけでは未知データへの性能や運用中の変化を判断できない。独立したテストデータで受け入れ基準を確認し、配備方法、監視指標、異常時の切戻し、再学習の条件を決める。ML開発は一度の学習で終わらず、運用監視まで含む反復的な流れである。',
    reviewerStatus: 'reviewed',
  },
  {
    id: 'ct-ai-010',
    sectionRef: '3.3',
    sourcePolicy: 'original',
    officialQuestionUsed: false,
    certificationReference: 'JSTQB CT-AI syllabus v1.0 referenced only as topic map',
    loCode: 'AI-3.3',
    kLevel: 'K3',
    topic: 'MLの形態の選択',
    question: '通信会社には解約済み顧客の履歴と解約有無の記録が十分にあり、現契約者の翌月解約を予測したい。最も適した学習の形態はどれか。',
    choices: ['（A）正解ラベルを使わず顧客を似た群に分ける教師なし学習', '（B）行動のたびに報酬を与える強化学習', '（C）過去の解約有無をラベルとして分類する教師あり学習', '（D）入力データを使わず乱数だけで予測する方法'],
    correctAnswerIndex: 2,
    explanation: '予測対象である解約有無が過去データに正解ラベルとして存在するため、教師あり分類が適している。教師なし学習は顧客群の探索には使えるが、解約という既知の目的変数を直接学ぶ選択ではない。評価時には時系列を考慮し、未来情報の混入を防ぐ必要もある。',
    reviewerStatus: 'reviewed',
  },
  {
    id: 'ct-ai-011',
    sectionRef: '3.3',
    sourcePolicy: 'original',
    officialQuestionUsed: false,
    certificationReference: 'JSTQB CT-AI syllabus v1.0 referenced only as topic map',
    loCode: 'AI-3.3',
    kLevel: 'K3',
    topic: 'MLの形態の選択',
    question: '倉庫ロボットに、混雑状況が変わる通路で衝突を避けながら短時間で搬送する方策を学ばせたい。成功時と衝突時の評価値を与えられる。最も適した学習の形態はどれか。',
    choices: ['（A）行動結果の報酬を基に方策を改善する強化学習', '（B）商品画像に品名ラベルを付ける教師あり学習', '（C）注文票を似た内容ごとに分ける教師なし学習', '（D）固定された最短経路を一度だけ登録する方法'],
    correctAnswerIndex: 0,
    explanation: 'ロボットが環境内で行動し、その結果として得る報酬を最大化する方策を学ぶ課題なので強化学習が適する。ただし、実環境で無制限に探索すると危険である。シミュレーション、行動制約、安全停止、未経験状態のテストを組み合わせて段階的に確認する。',
    reviewerStatus: 'reviewed',
  },
  {
    id: 'ct-ai-012',
    sectionRef: '3.5',
    sourcePolicy: 'original',
    officialQuestionUsed: false,
    certificationReference: 'JSTQB CT-AI syllabus v1.0 referenced only as topic map',
    loCode: 'AI-3.5',
    kLevel: 'K2',
    topic: 'オーバーフィッティングとアンダーフィッティング',
    question: '設備故障モデルは訓練データで99％、検証データで68％の正解率だった。追加の訓練を続けるほど差が広がっている。最も可能性が高い状態はどれか。',
    choices: ['（A）未知データにも十分適合している', '（B）モデルが単純すぎて訓練データも学べていない', '（C）評価指標が常に無意味である', '（D）訓練データへ過度に適合し、オーバーフィッティングしている'],
    correctAnswerIndex: 3,
    explanation: '訓練性能だけが非常に高く、独立した検証性能が低い状態は、訓練例の細部や雑音まで覚えた可能性を示す。データ追加、正則化、早期終了、特徴量やモデル複雑度の見直しを検討し、調整に使っていないテストデータで最終性能を確認する。',
    reviewerStatus: 'reviewed',
  },
  {
    id: 'ct-ai-013',
    sectionRef: '4.1',
    sourcePolicy: 'original',
    officialQuestionUsed: false,
    certificationReference: 'JSTQB CT-AI syllabus v1.0 referenced only as topic map',
    loCode: 'AI-4.1',
    kLevel: 'K2',
    topic: 'MLワークフローの一環としてのデータ準備',
    question: '店舗売上モデルの準備中、欠損値を全データの平均で補完してから訓練用とテスト用に分割した。テスト担当者が指摘すべき問題はどれか。',
    choices: ['（A）平均値は数値なのでモデルへ入力できない', '（B）テストデータの情報が補完値を通じて訓練工程へ漏れる', '（C）欠損値は必ず行ごと削除しなければならない', '（D）分割後は訓練データを一切加工できない'],
    correctAnswerIndex: 1,
    explanation: '全データから計算した平均にはテスト部分の情報も含まれるため、実運用より有利な評価になる可能性がある。先にデータを分割し、補完規則や尺度変換の値は訓練データだけで決定する。その同じ変換を検証用とテスト用へ適用し、情報漏えいを防ぐ。',
    reviewerStatus: 'reviewed',
  },
  {
    id: 'ct-ai-014',
    sectionRef: '4.2',
    sourcePolicy: 'original',
    officialQuestionUsed: false,
    certificationReference: 'JSTQB CT-AI syllabus v1.0 referenced only as topic map',
    loCode: 'AI-4.2',
    kLevel: 'K2',
    topic: '訓練・検証・テストデータセット',
    question: '商品分類モデルで、同じテストデータを見ながら特徴量としきい値を何度も調整した。最後に得たテスト成績を信頼しにくい主な理由はどれか。',
    choices: ['（A）テストデータが調整判断に使われ、実質的にモデル開発へ組み込まれたため', '（B）特徴量は一度も変更してはいけないため', '（C）テストデータは訓練データより必ず多くすべきため', '（D）しきい値を持つモデルは評価できないため'],
    correctAnswerIndex: 0,
    explanation: 'テスト結果を見て設計やしきい値を繰り返し変更すると、そのデータに合わせた最適化が進み、未知データへの性能を過大評価しやすい。調整には検証データを使い、最終決定後に隔離していたテストデータを一度だけ用いる運用が望ましい。',
    reviewerStatus: 'reviewed',
  },
  {
    id: 'ct-ai-015',
    sectionRef: '4.3',
    sourcePolicy: 'original',
    officialQuestionUsed: false,
    certificationReference: 'JSTQB CT-AI syllabus v1.0 referenced only as topic map',
    loCode: 'AI-4.3',
    kLevel: 'K2',
    topic: 'データセットの品質問題',
    question: '音声認識モデルのデータを調査すると、静かな会議室の録音が大半で、工場内の録音がほとんどなかった。工場で利用する場合の主要な品質問題はどれか。',
    choices: ['（A）録音ファイル名が連番になっていること', '（B）音声データの容量が大きいこと', '（C）利用環境を代表しておらず、工場騒音下の性能を評価できないこと', '（D）会議室で録音した話者が複数いること'],
    correctAnswerIndex: 2,
    explanation: 'データ件数が多くても、実際の利用条件を十分に含まなければ代表性が低い。騒音の種類、音量、マイク、話者属性など工場で想定する条件を分析し、不足する組合せを収集する。条件別の性能も測定し、平均値だけで弱点を隠さないことが重要である。',
    reviewerStatus: 'reviewed',
  },
  {
    id: 'ct-ai-016',
    sectionRef: '4.4',
    sourcePolicy: 'original',
    officialQuestionUsed: false,
    certificationReference: 'JSTQB CT-AI syllabus v1.0 referenced only as topic map',
    loCode: 'AI-4.4',
    kLevel: 'K2',
    topic: 'データ品質とMLモデルへの影響',
    question: '保守記録から故障原因を分類するモデルで、同じ症状なのに担当者ごとに異なる原因ラベルが付いている。予想される影響として最も適切なものはどれか。',
    choices: ['（A）モデルの保存容量だけが増え、予測には影響しない', '（B）正解関係が曖昧になり、学習可能な性能の上限が下がる', '（C）ラベルが多様なほど必ず汎化性能が上がる', '（D）入力特徴量が正しければラベルの不一致は無視できる'],
    correctAnswerIndex: 1,
    explanation: '同一条件に矛盾したラベルが付くと、モデルは入力と正解の安定した関係を学びにくくなる。ラベル定義を明確にし、複数担当者の一致度を測り、不一致例を専門家が再確認する。修正前後で性能を比較すれば、データ品質改善の効果も把握できる。',
    reviewerStatus: 'reviewed',
  },
  {
    id: 'ct-ai-017',
    sectionRef: '5.1',
    sourcePolicy: 'original',
    officialQuestionUsed: false,
    certificationReference: 'JSTQB CT-AI syllabus v1.0 referenced only as topic map',
    loCode: 'AI-5.1',
    kLevel: 'K3',
    topic: '混同行列',
    question: '不良品検出モデルを1000個で評価した。不良品100個のうち80個を不良と判定し、正常品900個のうち45個を誤って不良と判定した。偽陰性の件数はいくつか。',
    choices: ['（A）20件', '（B）45件', '（C）80件', '（D）855件'],
    correctAnswerIndex: 0,
    explanation: '偽陰性は、実際には陽性である不良品を陰性、つまり正常と誤判定した件数である。不良品100個のうち80個を正しく不良と検出したため、残る20個が偽陰性となる。45個は正常品を不良とした偽陽性であり、取り違えないことが重要である。',
    reviewerStatus: 'reviewed',
  },
  {
    id: 'ct-ai-018',
    sectionRef: '5.1',
    sourcePolicy: 'original',
    officialQuestionUsed: false,
    certificationReference: 'JSTQB CT-AI syllabus v1.0 referenced only as topic map',
    loCode: 'AI-5.1',
    kLevel: 'K3',
    topic: '混同行列',
    question: '迷惑メール判定を200件で評価した。迷惑メール50件のうち40件を検出し、通常メール150件のうち15件を迷惑メールと誤判定した。適合率に最も近い値はどれか。',
    choices: ['（A）40％', '（B）60％', '（C）73％', '（D）80％'],
    correctAnswerIndex: 2,
    explanation: '適合率は、陽性と予測したもののうち実際に陽性だった割合であり、真陽性を真陽性と偽陽性の合計で割る。この例では40÷（40＋15）で約0.727、約73％となる。80％は再現率であり、目的に応じて両者を区別する必要がある。',
    reviewerStatus: 'reviewed',
  },
  {
    id: 'ct-ai-019',
    sectionRef: '5.2',
    sourcePolicy: 'original',
    officialQuestionUsed: false,
    certificationReference: 'JSTQB CT-AI syllabus v1.0 referenced only as topic map',
    loCode: 'AI-5.2',
    kLevel: 'K2',
    topic: '追加メトリクス',
    question: '病変候補の検出では見逃しも過剰検出も抑えたい。適合率と再現率を一つの値で均衡して比較するため、追加で見る指標として最も適切なものはどれか。',
    choices: ['（A）ファイルサイズ', '（B）F1値', '（C）学習回数', '（D）画面の描画速度'],
    correctAnswerIndex: 1,
    explanation: 'F1値は適合率と再現率の調和平均であり、どちらか一方だけが高いモデルを過大評価しにくい。ただし、見逃しと過剰検出の損失が同じとは限らないため、F1値だけで決めず、個別指標、しきい値ごとの変化、業務上の損失も合わせて確認する。',
    reviewerStatus: 'reviewed',
  },
  {
    id: 'ct-ai-020',
    sectionRef: '5.3',
    sourcePolicy: 'original',
    officialQuestionUsed: false,
    certificationReference: 'JSTQB CT-AI syllabus v1.0 referenced only as topic map',
    loCode: 'AI-5.3',
    kLevel: 'K2',
    topic: 'メトリクスの限界',
    question: '不正取引が全体の0.1％しかないデータで、すべて正常と答えるモデルが99.9％の正解率を得た。評価上の問題として最も適切なものはどれか。',
    choices: ['（A）正解率が高いので不正検出にも十分使える', '（B）データ件数が多すぎるため評価できない', '（C）不正取引のラベルを正常へ変更すべきである', '（D）クラス不均衡により、正解率だけでは不正を一件も検出できない弱点が隠れる'],
    correctAnswerIndex: 3,
    explanation: '多数派だけを予測しても高い正解率になるため、希少事象の検出能力を正解率だけで判断できない。混同行列、再現率、適合率、適合率と再現率の曲線などを確認し、見逃しと誤警報の業務コストに沿ってしきい値と受け入れ基準を設定する。',
    reviewerStatus: 'reviewed',
  },
  {
    id: 'ct-ai-021',
    sectionRef: '5.4',
    sourcePolicy: 'original',
    officialQuestionUsed: false,
    certificationReference: 'JSTQB CT-AI syllabus v1.0 referenced only as topic map',
    loCode: 'AI-5.4',
    kLevel: 'K4',
    topic: 'メトリクスの選択',
    question: '空港の危険物検査支援では、見逃しの損失が誤警報による再検査の損失よりはるかに大きい。候補モデルを比較する指標の組合せとして最も適切なものはどれか。',
    choices: ['（A）全体正解率だけを最大化する', '（B）学習時間だけを最小化する', '（C）再現率を重視しつつ、許容可能な誤警報率と処理時間も確認する', '（D）モデルのパラメータ数だけを最小化する'],
    correctAnswerIndex: 2,
    explanation: '危険物の見逃しが重大なら、陽性をどれだけ捕捉できるかを示す再現率を重視する。ただし再現率を上げるだけでは誤警報が急増し、現場が処理不能になる恐れがある。許容する偽陽性率、処理能力、遅延を合わせ、損失と運用制約に基づいて選ぶ。',
    reviewerStatus: 'reviewed',
  },
  {
    id: 'ct-ai-022',
    sectionRef: '5.4',
    sourcePolicy: 'original',
    officialQuestionUsed: false,
    certificationReference: 'JSTQB CT-AI syllabus v1.0 referenced only as topic map',
    loCode: 'AI-5.4',
    kLevel: 'K4',
    topic: 'メトリクスの選択',
    question: '動画配信会社が解約確率を出す二つのモデルを比較する。営業部門は上位5％の顧客だけに連絡でき、連絡対象内の実際の解約者割合を高めたい。最優先の指標はどれか。',
    choices: ['（A）上位5％における適合率', '（B）全顧客に対する平均二乗誤差だけ', '（C）訓練データの正解率だけ', '（D）モデルファイルの圧縮率'],
    correctAnswerIndex: 0,
    explanation: '対応可能人数が上位5％に限られるため、その範囲で実際の解約者がどれだけ含まれるかが業務成果に直結する。上位群の適合率やリフトを比較し、接触費用と解約防止効果も評価する。全体平均の指標が良くても、上位順位の品質が良いとは限らない。',
    reviewerStatus: 'reviewed',
  },
  {
    id: 'ct-ai-023',
    sectionRef: '6.1',
    sourcePolicy: 'original',
    officialQuestionUsed: false,
    certificationReference: 'JSTQB CT-AI syllabus v1.0 referenced only as topic map',
    loCode: 'AI-6.1',
    kLevel: 'K2',
    topic: 'ニューラルネットワーク',
    question: '画像分類用ニューラルネットワークで、中間層の活性化関数をすべて線形関数に変更した。深い層を重ねる利点が大きく失われる理由はどれか。',
    choices: ['（A）画像を数値として入力できなくなるため', '（B）重みを保存できなくなるため', '（C）出力クラスが必ず一つになるため', '（D）線形変換を重ねても全体として一つの線形変換にまとめられるため'],
    correctAnswerIndex: 3,
    explanation: '線形変換だけを何層重ねても、合成結果は一つの線形変換として表せるため、複雑な非線形境界を学ぶ表現力が得られない。活性化関数による非線形性が、画像の階層的な特徴を表現するうえで重要である。変更時は性能だけでなく勾配の挙動も確認する。',
    reviewerStatus: 'reviewed',
  },
  {
    id: 'ct-ai-024',
    sectionRef: '7.1',
    sourcePolicy: 'original',
    officialQuestionUsed: false,
    certificationReference: 'JSTQB CT-AI syllabus v1.0 referenced only as topic map',
    loCode: 'AI-7.1',
    kLevel: 'K2',
    topic: '仕様',
    question: '問い合わせ分類モデルの要求が「十分に正確であること」とだけ記載されている。テスト可能な仕様へ改善する案として最も適切なものはどれか。',
    choices: ['（A）開発者が良いと感じれば合格とする', '（B）対象データ、クラス別指標、最低値、応答時間、例外時の動作を定める', '（C）モデルの内部構造だけを細かく指定する', '（D）訓練データで一件でも正解すれば合格とする'],
    correctAnswerIndex: 1,
    explanation: '曖昧な品質表現では、合否判断や再現可能な評価ができない。利用場面を代表するデータ範囲、重要クラス別の性能、許容遅延、低信頼時の処理、監視条件を測定可能な形で定める。確率的な出力では、個々の完全一致より統計的な基準が適する場合もある。',
    reviewerStatus: 'reviewed',
  },
  {
    id: 'ct-ai-025',
    sectionRef: '7.2',
    sourcePolicy: 'original',
    officialQuestionUsed: false,
    certificationReference: 'JSTQB CT-AI syllabus v1.0 referenced only as topic map',
    loCode: 'AI-7.2',
    kLevel: 'K2',
    topic: 'テストレベル',
    question: '顔照合モデル単体では目標精度を満たしたが、入退室システムではカメラ圧縮後の画像で誤拒否が増えた。この問題を検出するのに最も適したテストレベルはどれか。',
    choices: ['（A）モデルの数式だけを確認する静的な確認', '（B）学習処理の一関数だけを対象にする単体テスト', '（C）カメラ、前処理、モデル、判定処理を結合したシステムテスト', '（D）変数名の命名規則だけを確認するレビュー'],
    correctAnswerIndex: 2,
    explanation: 'モデル単体の評価では、実際のカメラ圧縮、画像前処理、しきい値、後続処理との相互作用を捉えられない。利用環境に近い構成でシステム全体を通し、条件別の誤拒否率を確認する。低いテストレベルも必要だが、統合後に生じる品質問題は別途検証する。',
    reviewerStatus: 'reviewed',
  },
  {
    id: 'ct-ai-026',
    sectionRef: '7.6',
    sourcePolicy: 'original',
    officialQuestionUsed: false,
    certificationReference: 'JSTQB CT-AI syllabus v1.0 referenced only as topic map',
    loCode: 'AI-7.6',
    kLevel: 'K2',
    topic: 'コンセプトドリフトテスト',
    question: '感染症流行後、飲食店の来客予測が急に外れるようになった。入力項目の形式や欠損率は以前とほぼ同じである。最も疑うべき変化はどれか。',
    choices: ['（A）曜日や天候と来客数の関係自体が変化したコンセプトドリフト', '（B）モデルファイル名の長さの変化', '（C）画面配色の変化', '（D）開発者の人数の変化'],
    correctAnswerIndex: 0,
    explanation: '入力形式が同じでも、生活様式の変化により曜日や天候から来客数へ至る関係が変われば、過去に学んだ対応が通用しなくなる。時期別の誤差や条件付き分布を比較し、ドリフトを確認する。必要なら直近データで再学習し、更新前後を独立データで評価する。',
    reviewerStatus: 'reviewed',
  },
  {
    id: 'ct-ai-027',
    sectionRef: '7.7',
    sourcePolicy: 'original',
    officialQuestionUsed: false,
    certificationReference: 'JSTQB CT-AI syllabus v1.0 referenced only as topic map',
    loCode: 'AI-7.7',
    kLevel: 'K4',
    topic: 'テスト手法の選択',
    question: '自動運転支援の歩行者検出を評価する。実事故データは少なく、天候、時間帯、服装、遮蔽の組合せが膨大で、見逃しは重大である。最も適切なテスト方針はどれか。',
    choices: ['（A）晴天昼間の実画像だけで正解率を測る', '（B）実データだけが十分になるまでテストを延期する', '（C）開発者が選んだ成功例だけを再生する', '（D）リスク分析で条件を優先し、実データ、生成データ、仮想環境を組み合わせて境界条件を試す'],
    correctAnswerIndex: 3,
    explanation: '重大な見逃しと広い入力空間があるため、単一のデータ源では十分な条件を覆えない。リスクの高い組合せを特定し、希少条件を生成データや仮想環境で補い、代表的な実データで妥当性を確認する。条件別の再現率と失敗例を追跡し、残るリスクも明示する。',
    reviewerStatus: 'reviewed',
  },
  {
    id: 'ct-ai-028',
    sectionRef: '7.7',
    sourcePolicy: 'original',
    officialQuestionUsed: false,
    certificationReference: 'JSTQB CT-AI syllabus v1.0 referenced only as topic map',
    loCode: 'AI-7.7',
    kLevel: 'K4',
    topic: 'テスト手法の選択',
    question: '文書要約モデルには唯一の正解文がなく、入力表現の小変更に対する安定性と、重要事項を落とさないことを確認したい。最適な手法の組合せはどれか。',
    choices: ['（A）出力文字列が一字一句固定値と一致することだけを確認する', '（B）メタモルフィックテスト、専門家評価、重要事項のチェックリストを組み合わせる', '（C）応答時間だけを測り、内容は評価しない', '（D）訓練データと同じ文書だけを入力する'],
    correctAnswerIndex: 1,
    explanation: '要約には複数の妥当な表現があり、固定文字列との一致だけでは品質を測れない。意味を保つ入力変換に対する関係を確認し、専門家が正確性や欠落を評価し、重要事項の保持をチェックする。自動指標も補助に使えるが、人の判断との相関を確かめる必要がある。',
    reviewerStatus: 'reviewed',
  },
  {
    id: 'ct-ai-029',
    sectionRef: '8.8',
    sourcePolicy: 'original',
    officialQuestionUsed: false,
    certificationReference: 'JSTQB CT-AI syllabus v1.0 referenced only as topic map',
    loCode: 'AI-8.8',
    kLevel: 'K4',
    topic: 'テスト目的と受け入れ基準',
    question: '救急相談の緊急度分類で、最優先患者の見逃しを抑えつつ、相談員が処理できる警告件数に収めたい。最も適切な受け入れ基準はどれか。',
    choices: ['（A）全体正解率90％以上だけを条件にする', '（B）訓練が一時間以内に終わることだけを条件にする', '（C）最優先群の再現率下限と、一時間当たりの偽警告上限を代表データで満たす', '（D）一つの成功例で期待どおりなら合格とする'],
    correctAnswerIndex: 2,
    explanation: 'テスト目的は重大な見逃しの抑制と運用可能な警告量の両立であるため、両方を測る基準が必要になる。重要群の再現率下限、偽警告数の上限、信頼区間、対象条件を明記する。全体正解率だけでは少数の最優先患者に対する弱点を隠す恐れがある。',
    reviewerStatus: 'reviewed',
  },
  {
    id: 'ct-ai-030',
    sectionRef: '8.8',
    sourcePolicy: 'original',
    officialQuestionUsed: false,
    certificationReference: 'JSTQB CT-AI syllabus v1.0 referenced only as topic map',
    loCode: 'AI-8.8',
    kLevel: 'K4',
    topic: 'テスト目的と受け入れ基準',
    question: '生成モデルを社内問い合わせへ導入する。目的は、根拠のない回答を抑え、担当者の確認時間を短縮することである。受け入れ基準として最も適切なものはどれか。',
    choices: ['（A）モデルの回答文字数が常に同じであること', '（B）評価用質問で根拠提示率と重大な誤回答率の基準を満たし、確認時間も目標内であること', '（C）一度でも自然な文章を生成できること', '（D）開発者がすべての回答を好ましいと感じること'],
    correctAnswerIndex: 1,
    explanation: '導入目的が誤回答の抑制と作業時間短縮なので、内容品質と運用効果の双方を測る必要がある。代表質問で根拠との整合性、重大な誤回答率、回答不能時の動作を評価し、実務試行で確認時間を測る。主観だけに頼らず、判定手順と標本数も定める。',
    reviewerStatus: 'reviewed',
  },
  {
    id: 'ct-ai-031',
    sectionRef: '9.1',
    sourcePolicy: 'original',
    officialQuestionUsed: false,
    certificationReference: 'JSTQB CT-AI syllabus v1.0 referenced only as topic map',
    loCode: 'AI-9.1',
    kLevel: 'K2',
    topic: '敵対的攻撃とデータポイズニング',
    question: '公開フォームから集めた画像で商品分類モデルを毎週再学習している。攻撃者が特定商品を別カテゴリに分類させる目的で、誤ったラベルの画像を大量投稿した。これは何に当たるか。',
    choices: ['（A）本番入力だけを微小変更する敵対的サンプル', '（B）処理速度を測る性能テスト', '（C）入力分布の自然な季節変動', '（D）訓練データを汚染して学習結果を操作するデータポイズニング'],
    correctAnswerIndex: 3,
    explanation: '再学習に使われるデータへ意図的に誤情報を混ぜ、将来のモデル挙動を変える攻撃はデータポイズニングである。投稿元の信頼性、急増、重複、ラベル分布を監視し、隔離と人手確認を行う。再学習前後の固定評価セットによる比較も異常検出に役立つ。',
    reviewerStatus: 'reviewed',
  },
  {
    id: 'ct-ai-032',
    sectionRef: '9.5',
    sourcePolicy: 'original',
    officialQuestionUsed: false,
    certificationReference: 'JSTQB CT-AI syllabus v1.0 referenced only as topic map',
    loCode: 'AI-9.5',
    kLevel: 'K3',
    topic: 'メタモルフィックテスト（MT）',
    question: '道路標識分類器には、あらゆる画像の正解ラベルを用意できない。元画像の明るさを安全な範囲で少し変えた画像を作る場合、適切なメタモルフィック関係はどれか。',
    choices: ['（A）明るさ変更後は必ず別の標識クラスになる', '（B）標識の意味が見える範囲なら、分類結果は元画像と同じである', '（C）明るさ変更後の処理時間は必ずゼロになる', '（D）画素数が同じなら信頼度は必ず完全一致する'],
    correctAnswerIndex: 1,
    explanation: '意味を変えない程度の明るさ変更なら、標識クラスも変わらないという関係を期待できる。個々の派生画像に新しい正解を付けなくても、元出力との関係から問題を検出できる。ただし、視認不能になる変換は前提を破るため、変換範囲を明確に定義して使う。',
    reviewerStatus: 'reviewed',
  },
  {
    id: 'ct-ai-033',
    sectionRef: '9.5',
    sourcePolicy: 'original',
    officialQuestionUsed: false,
    certificationReference: 'JSTQB CT-AI syllabus v1.0 referenced only as topic map',
    loCode: 'AI-9.5',
    kLevel: 'K3',
    topic: 'メタモルフィックテスト（MT）',
    question: '住宅価格予測モデルで、他の条件をすべて固定し、床面積だけを80平方メートルから100平方メートルへ増やした派生入力を作る。業務知識上、適切な関係はどれか。',
    choices: ['（A）予測価格は必ず半分になる', '（B）予測価格は必ず一円単位で同じになる', '（C）通常条件では予測価格が低下しないことを確認する', '（D）床面積を変えると所在地も自動的に変わることを確認する'],
    correctAnswerIndex: 2,
    explanation: '所在地や築年数などを固定し床面積だけを増やすなら、通常は価格が下がらないという単調関係を設定できる。正確な価格を知らなくても、関係違反から不自然な挙動を発見できる。ただし特殊物件など例外条件を整理し、適用範囲を限定して判定する必要がある。',
    reviewerStatus: 'reviewed',
  },
  {
    id: 'ct-ai-034',
    sectionRef: '9.7',
    sourcePolicy: 'original',
    officialQuestionUsed: false,
    certificationReference: 'JSTQB CT-AI syllabus v1.0 referenced only as topic map',
    loCode: 'AI-9.7',
    kLevel: 'K4',
    topic: 'テスト技法の選択',
    question: '検索順位モデルを新モデルへ切り替えたい。正解順位は利用者ごとに異なり、現行モデルとの品質差と実利用時のクリック率への影響を段階的に確認したい。最適な技法の組合せはどれか。',
    choices: ['（A）オフラインで現行モデルとのバックツーバック比較を行い、その後に限定的なA/Bテストを行う', '（B）新モデルを全利用者へ即時公開し、問題報告だけを待つ', '（C）ソースコードの行数だけを比較する', '（D）訓練データで新モデルの出力を一件だけ確認する'],
    correctAnswerIndex: 0,
    explanation: 'まず同一入力に対する両モデルの差を大量に調べれば、順位変動や極端な退行を公開前に把握できる。その後、対象を限定したA/Bテストで実利用者の行動指標を比較する。停止条件、標本数、利用者群の偏りを管理し、安全に段階導入する方針が適切である。',
    reviewerStatus: 'reviewed',
  },
  {
    id: 'ct-ai-035',
    sectionRef: '9.7',
    sourcePolicy: 'original',
    officialQuestionUsed: false,
    certificationReference: 'JSTQB CT-AI syllabus v1.0 referenced only as topic map',
    loCode: 'AI-9.7',
    kLevel: 'K4',
    topic: 'テスト技法の選択',
    question: '農作物病害診断モデルで、病害の組合せ、撮影端末、天候、成長段階が多く、全組合せは試せない。さらに画像の一部には正解付与が難しい。最も適切なテスト方針はどれか。',
    choices: ['（A）最も多い一条件だけを繰り返し試す', '（B）正解が難しいため、内容に関するテストをすべて省く', '（C）ランダムに一枚だけ選び、成功すれば終了する', '（D）ペアワイズで条件組合せを絞り、重要条件は追加し、正解困難な画像には関係性テストや専門家評価を使う'],
    correctAnswerIndex: 3,
    explanation: '組合せ爆発にはペアワイズで基本的な相互作用を効率よく覆い、重大な病害や既知の高リスク条件は明示的に追加する。正解が一意に定めにくい画像には、意味を保つ変換での関係性確認や専門家評価を組み合わせる。技法は制約とリスクに応じて補完的に選ぶ。',
    reviewerStatus: 'reviewed',
  },
];
