// 制作者が独自に作成したCT-GenAI学習問題。公式問題・公式本文は使用しない。

export const questions = [
  {
    id: 'ct-genai-001',
    sectionRef: '1.1',
    sourcePolicy: 'original',
    officialQuestionUsed: false,
    certificationReference: 'ISTQB CT-GenAI syllabus v1.1 referenced only as topic map',
    loCode: 'GenAI-1.1',
    kLevel: 'K2',
    topic: '生成AIの基礎と主要概念',
    question: 'テストチームが大規模言語モデルに障害報告の要約を依頼したところ、同じ入力でも表現が少しずつ変わりました。この現象を最も適切に説明するものはどれですか。',
    choices: ['出力候補を確率的に選択する仕組みが影響している', '入力文がモデル内部で永久保存されるためである', 'モデルが毎回新しい学習データを収集するためである', '要約処理では入力内容が参照されないためである'],
    correctAnswerIndex: 0,
    explanation: '大規模言語モデルは、文脈に続く語の確率分布に基づいて出力を生成します。温度などの設定や候補選択の過程により、同じ入力でも表現が変わることがあります。重要なテスト成果物では、設定の固定、複数回の確認、人によるレビューが必要です。',
    reviewerStatus: 'reviewed',
  },
  {
    id: 'ct-genai-002',
    sectionRef: '1.1',
    sourcePolicy: 'original',
    officialQuestionUsed: false,
    certificationReference: 'ISTQB CT-GenAI syllabus v1.1 referenced only as topic map',
    loCode: 'GenAI-1.1',
    kLevel: 'K2',
    topic: '生成AIの基礎と主要概念',
    question: 'テスト設計支援に使う言語モデルについて、チームメンバーが「モデルは要求仕様を人間と同じ意味で理解している」と説明しました。より適切な理解はどれですか。',
    choices: ['モデルは常に業務上の真実を保持している', 'モデルは入力から規則を実行するだけで文章を生成しない', 'モデルは学習したパターンと文脈からもっともらしい文章を生成する', 'モデルは根拠資料がなくても事実だけを回答する'],
    correctAnswerIndex: 2,
    explanation: '言語モデルは大量のデータから得たパターンと入力文脈を利用し、もっともらしい応答を生成します。人間と同じ理解や業務知識の正しさが保証されるわけではありません。そのため、要求との対応、前提、根拠を別途確認し、最終判断を担当者が行います。',
    reviewerStatus: 'reviewed',
  },
  {
    id: 'ct-genai-003',
    sectionRef: '1.2',
    sourcePolicy: 'original',
    officialQuestionUsed: false,
    certificationReference: 'ISTQB CT-GenAI syllabus v1.1 referenced only as topic map',
    loCode: 'GenAI-1.2',
    kLevel: 'K2',
    topic: 'ソフトウェアテストへの生成AI活用の基本原則',
    question: '生成AIが作成した決済機能のテストケースを、そのまま回帰テストへ追加する案が出ました。テストリーダーが最初に行うべき対応はどれですか。',
    choices: ['件数が多ければ品質が高いと判断する', '要求との対応や重複、実行可能性を担当者がレビューする', '生成時刻が新しければ無条件で採用する', '既存テストをすべて削除して置き換える'],
    correctAnswerIndex: 1,
    explanation: '生成されたテストケースには、要求の誤読、重複、実行不能な手順、誤った期待結果が含まれ得ます。採用前に要求との追跡性、リスクへの寄与、データや環境の実現性を人が確認すべきです。生成AIは設計を支援しますが、品質責任や採否判断はチームに残ります。',
    reviewerStatus: 'reviewed',
  },
  {
    id: 'ct-genai-004',
    sectionRef: '1.2',
    sourcePolicy: 'original',
    officialQuestionUsed: false,
    certificationReference: 'ISTQB CT-GenAI syllabus v1.1 referenced only as topic map',
    loCode: 'GenAI-1.2',
    kLevel: 'K2',
    topic: 'ソフトウェアテストへの生成AI活用の基本原則',
    question: 'チームが生成AIによるテスト分析の効果を試したいと考えています。導入初期の進め方として最も適切なものはどれですか。',
    choices: ['目的と評価指標を決め、小規模な対象で人の作業と比較する', '全案件へ同時導入し、問題が出てから用途を決める', '出力速度だけを測り、欠陥検出への影響は測らない', '利用者ごとに異なる手順と判断基準を採用する'],
    correctAnswerIndex: 0,
    explanation: '導入効果は、時間短縮だけでなく、欠陥検出、網羅性、修正工数、誤出力の割合など複数の観点で測ります。まず限定した作業で基準値と比較すれば、利益とリスクを低コストで把握できます。目的、利用条件、レビュー方法もそろえると再現性のある判断ができます。',
    reviewerStatus: 'reviewed',
  },
  {
    id: 'ct-genai-005',
    sectionRef: '2.1',
    sourcePolicy: 'original',
    officialQuestionUsed: false,
    certificationReference: 'ISTQB CT-GenAI syllabus v1.1 referenced only as topic map',
    loCode: 'GenAI-2.1',
    kLevel: 'K2',
    topic: '効果的なプロンプトの作り方',
    question: '会員登録画面の境界値テストを生成させる際、最も効果的なプロンプトの特徴はどれですか。',
    choices: ['「よいテストを作って」とだけ指示する', '画面名だけを示し、制約はモデルに推測させる', '大量の無関係な設計資料を説明なしで添付する', '役割、入力制約、出力形式、対象外事項を具体的に示す'],
    correctAnswerIndex: 3,
    explanation: '役割、目的、入力条件、期待する出力形式、対象範囲を明示すると、モデルが解くべき課題の曖昧さを減らせます。たとえば文字数の上下限、必須項目、表形式の列を指定します。一方、情報不足や無関係な文脈の追加は、推測や重要条件の見落としを招きやすくなります。',
    reviewerStatus: 'reviewed',
  },
  {
    id: 'ct-genai-006',
    sectionRef: '2.1',
    sourcePolicy: 'original',
    officialQuestionUsed: false,
    certificationReference: 'ISTQB CT-GenAI syllabus v1.1 referenced only as topic map',
    loCode: 'GenAI-2.1',
    kLevel: 'K2',
    topic: '効果的なプロンプトの作り方',
    question: '障害報告から再現手順を抽出させましたが、回答の形式が毎回異なり自動処理できません。プロンプトの改善として最も適切なものはどれですか。',
    choices: ['回答を短くするよう感情的に強調する', '必要な項目と構造を示した出力例を与える', '同じ指示を意味なく何度も繰り返す', '障害報告を削除し、題名だけを入力する'],
    correctAnswerIndex: 1,
    explanation: '後続処理で一定の構造が必要なら、項目名、順序、許容値、空欄時の扱いを指定し、望ましい出力例を示す方法が有効です。例は形式上の期待を具体化します。ただし例の内容へ過度に引きずられないよう、異なる入力で検証し、構造検査も併用します。',
    reviewerStatus: 'reviewed',
  },
  {
    id: 'ct-genai-007',
    sectionRef: '2.2',
    sourcePolicy: 'original',
    officialQuestionUsed: false,
    certificationReference: 'ISTQB CT-GenAI syllabus v1.1 referenced only as topic map',
    loCode: 'GenAI-2.2',
    kLevel: 'K3',
    topic: 'テスト作業へのプロンプトエンジニアリング技法の適用',
    question: '航空券検索の仕様から同値分割のテストを作らせたところ、正常系しか出ませんでした。次に適用するプロンプトとして最も適切なものはどれですか。',
    choices: ['「もっと考えて」とだけ追記する', '正常系の件数だけを増やすよう依頼する', '各入力条件について有効・無効クラスを列挙し、根拠と代表値を表で出すよう指示する', 'モデルの自由度を上げるため仕様を入力しない'],
    correctAnswerIndex: 2,
    explanation: '不足が無効クラスにあると分かったため、テスト技法の手順と必要な列を明示して再生成します。有効・無効クラス、代表値、期待結果、仕様根拠を出させれば、抜けを比較しやすくなります。「もっと考えて」のような抽象的指示では、改善箇所をモデルへ十分伝えられません。',
    reviewerStatus: 'reviewed',
  },
  {
    id: 'ct-genai-008',
    sectionRef: '2.2',
    sourcePolicy: 'original',
    officialQuestionUsed: false,
    certificationReference: 'ISTQB CT-GenAI syllabus v1.1 referenced only as topic map',
    loCode: 'GenAI-2.2',
    kLevel: 'K3',
    topic: 'テスト作業へのプロンプトエンジニアリング技法の適用',
    question: '複雑な状態遷移仕様からテストシナリオを生成する際、モデルが遷移条件を混同しています。適用する方法として最も適切なものはどれですか。',
    choices: ['状態、イベント、ガード条件を整理させ、その結果を基に段階的にシナリオ化する', '一度の指示で最終成果物だけを大量生成させる', '遷移表を与えず一般知識だけで作らせる', '誤りを避けるため期待結果をすべて空欄にする'],
    correctAnswerIndex: 0,
    explanation: '複雑な課題は、仕様要素の抽出、遷移の整理、経路の選択、シナリオ化へ分割すると中間結果を確認できます。状態やガード条件の誤読を早い段階で修正でき、最終出力の根拠も追いやすくなります。ただし各段階の結果は元仕様と照合し、誤りの連鎖を防ぐ必要があります。',
    reviewerStatus: 'reviewed',
  },
  {
    id: 'ct-genai-009',
    sectionRef: '2.2',
    sourcePolicy: 'original',
    officialQuestionUsed: false,
    certificationReference: 'ISTQB CT-GenAI syllabus v1.1 referenced only as topic map',
    loCode: 'GenAI-2.2',
    kLevel: 'K3',
    topic: 'テスト作業へのプロンプトエンジニアリング技法の適用',
    question: 'API仕様からテストデータをJSON形式で生成し、テスト自動化へ渡します。誤ったデータの混入を減らす実装として最も適切なものはどれですか。',
    choices: ['自然文だけで出力させ、担当者が毎回手入力する', '出力件数が多ければ内容を検査しない', 'モデルの回答をそのまま本番環境へ送信する', '項目制約をプロンプトで示し、出力をスキーマ検証してから利用する'],
    correctAnswerIndex: 3,
    explanation: 'プロンプトで型、必須項目、値域、形式を指定するだけでなく、受け取ったJSONを機械的にスキーマ検証することが重要です。モデルは指定に反する値や余分な説明を返す場合があります。検証失敗時は再生成または人の確認へ回し、不正なデータが自動実行へ流れないようにします。',
    reviewerStatus: 'reviewed',
  },
  {
    id: 'ct-genai-010',
    sectionRef: '2.3',
    sourcePolicy: 'original',
    officialQuestionUsed: false,
    certificationReference: 'ISTQB CT-GenAI syllabus v1.1 referenced only as topic map',
    loCode: 'GenAI-2.3',
    kLevel: 'K2',
    topic: '生成AI結果の評価とプロンプトの改善',
    question: '二つのプロンプトで生成したテストケースの品質を比較します。評価方法として最も適切なものはどれですか。',
    choices: ['同じ代表入力と評価基準を使い、正確性や網羅性を比較する', '回答文が長い方を常に優れているとみなす', '各プロンプトを異なる仕様で試して単純比較する', '一度だけ生成し、偶然の差を考慮しない'],
    correctAnswerIndex: 0,
    explanation: 'プロンプトを公平に比較するには、同じ入力群、モデル設定、評価基準を用います。要求への正確性、リスクの網羅性、重複、実行可能性などを採点し、必要なら複数回生成して変動も確認します。文章量や印象だけでは、テスト成果物としての有用性を適切に判断できません。',
    reviewerStatus: 'reviewed',
  },
  {
    id: 'ct-genai-011',
    sectionRef: '2.3',
    sourcePolicy: 'original',
    officialQuestionUsed: false,
    certificationReference: 'ISTQB CT-GenAI syllabus v1.1 referenced only as topic map',
    loCode: 'GenAI-2.3',
    kLevel: 'K2',
    topic: '生成AI結果の評価とプロンプトの改善',
    question: '生成されたテストケースで、期待結果の誤りが繰り返し見つかりました。改善活動として最も適切なものはどれですか。',
    choices: ['誤りを記録せず、利用者の注意だけに頼る', '原因を分類し、根拠の引用と不明時の応答規則をプロンプトへ追加して再評価する', '期待結果の列を削除して誤りを見えなくする', '正しかった一件だけを基に品質を判断する'],
    correctAnswerIndex: 1,
    explanation: '誤りを仕様の取り違え、情報不足、形式不備などに分類すると、改善すべき指示を特定できます。根拠箇所の提示、推測禁止、不明時の明示といった規則を加え、同じ評価セットで再測定します。修正後も別の品質が低下していないか確認し、変更履歴を残すことが重要です。',
    reviewerStatus: 'reviewed',
  },
  {
    id: 'ct-genai-012',
    sectionRef: '3.1',
    sourcePolicy: 'original',
    officialQuestionUsed: false,
    certificationReference: 'ISTQB CT-GenAI syllabus v1.1 referenced only as topic map',
    loCode: 'GenAI-3.1',
    kLevel: 'K3',
    topic: 'ハルシネーション・推論エラー・バイアス',
    question: '生成AIが、入力した要求仕様に存在しない「返金は30日以内」という条件を根拠としてテストケースを作りました。チームの対応として最も適切なものはどれですか。',
    choices: ['自然な文章なので要求へ追加する', 'モデルが示した条件を無条件で正しいとする', '件数を増やせば誤った条件も有用になると考える', '根拠箇所を確認し、裏付けのないケースを除外して原因を記録する'],
    correctAnswerIndex: 3,
    explanation: '入力や信頼できる資料にない条件を事実のように生成したため、ハルシネーションとして扱います。根拠を照合し、影響するテストケースを修正または除外します。さらに、根拠引用の必須化、不明時に推測しない指示、検索対象の限定などを行い、再発率を測定します。',
    reviewerStatus: 'reviewed',
  },
  {
    id: 'ct-genai-013',
    sectionRef: '3.1',
    sourcePolicy: 'original',
    officialQuestionUsed: false,
    certificationReference: 'ISTQB CT-GenAI syllabus v1.1 referenced only as topic map',
    loCode: 'GenAI-3.1',
    kLevel: 'K3',
    topic: 'ハルシネーション・推論エラー・バイアス',
    question: '料金計算のテスト期待値を生成AIに計算させたところ、説明の手順はもっともらしいものの合計値が誤っていました。最も適切な対策はどれですか。',
    choices: ['文章が論理的なら数値を採用する', '計算式と中間値を構造化して出させ、別の計算処理で検算する', '温度を上げれば計算精度が必ず向上すると考える', '誤差をすべて仕様上の許容差として扱う'],
    correctAnswerIndex: 1,
    explanation: '言語モデルは説明文を自然に生成できても、算術や複数条件の推論を誤ることがあります。式、入力値、中間結果を分けて出力させると確認しやすくなります。期待値の確定には、決定的な計算コード、表計算、既知の参照値など独立した手段で検算するのが適切です。',
    reviewerStatus: 'reviewed',
  },
  {
    id: 'ct-genai-014',
    sectionRef: '3.1',
    sourcePolicy: 'original',
    officialQuestionUsed: false,
    certificationReference: 'ISTQB CT-GenAI syllabus v1.1 referenced only as topic map',
    loCode: 'GenAI-3.1',
    kLevel: 'K3',
    topic: 'ハルシネーション・推論エラー・バイアス',
    question: '採用管理システムのテスト人物像を生成したところ、特定の職種と性別を固定的に結び付けた例が多く含まれました。チームが取るべき対応はどれですか。',
    choices: ['実データにも偏りがあり得るため、そのまま利用する', '人物像を一種類に絞り比較を避ける', '偏りの観点を定め、多様な属性の組合せで出力を評価し修正する', '属性に関するテストをすべて中止する'],
    correctAnswerIndex: 2,
    explanation: '学習データや指示の影響で、モデルは社会的な固定観念を再現することがあります。属性の組合せや表現を評価し、不当な関連付けや欠落を特定します。目的に必要な範囲で多様な例を用意し、当事者への影響を人が確認して、偏った人物像がテスト設計へ混入するのを防ぎます。',
    reviewerStatus: 'reviewed',
  },
  {
    id: 'ct-genai-015',
    sectionRef: '3.2',
    sourcePolicy: 'original',
    officialQuestionUsed: false,
    certificationReference: 'ISTQB CT-GenAI syllabus v1.1 referenced only as topic map',
    loCode: 'GenAI-3.2',
    kLevel: 'K2',
    topic: 'データプライバシーとセキュリティリスク',
    question: '障害解析のため、利用者の氏名やメールアドレスを含む本番ログを外部の生成AIサービスへ入力する案が出ました。最初に行うべきことはどれですか。',
    choices: ['入力後に問題があれば削除を依頼する', '個人情報を含むほど回答精度が高いとみなす', '利用条件と組織方針を確認し、必要性を評価して匿名化や代替データを検討する', '担当者個人の判断だけで入力する'],
    correctAnswerIndex: 2,
    explanation: '外部サービスへの入力は、保存、二次利用、国外移転、アクセス権などのリスクを伴います。まず組織の規則、契約、利用目的、データ最小化の要件を確認します。個人情報が不要なら匿名化や合成データへ置き換え、必要な場合も承認された環境と手順だけを使用します。',
    reviewerStatus: 'reviewed',
  },
  {
    id: 'ct-genai-016',
    sectionRef: '3.2',
    sourcePolicy: 'original',
    officialQuestionUsed: false,
    certificationReference: 'ISTQB CT-GenAI syllabus v1.1 referenced only as topic map',
    loCode: 'GenAI-3.2',
    kLevel: 'K2',
    topic: 'データプライバシーとセキュリティリスク',
    question: '社内文書を検索する生成AIへ、取得した文書中の命令文をそのまま実行させる設計があります。主なセキュリティリスクはどれですか。',
    choices: ['文書内の悪意ある指示により、本来の指示や制約が上書きされる', '検索件数が少ないと必ず情報漏えいが起きる', '日本語の文書は検索できなくなる', '回答が短いほど権限が自動的に拡大する'],
    correctAnswerIndex: 0,
    explanation: '取得文書は信頼できない入力であり、そこにモデルへの命令を埋め込む間接的なプロンプト注入が起こり得ます。文書内容とシステム指示を分離し、許可する操作を限定します。外部処理の前には権限検査、入力無害化、出力検証、人の承認を組み合わせる必要があります。',
    reviewerStatus: 'reviewed',
  },
  {
    id: 'ct-genai-017',
    sectionRef: '3.2',
    sourcePolicy: 'original',
    officialQuestionUsed: false,
    certificationReference: 'ISTQB CT-GenAI syllabus v1.1 referenced only as topic map',
    loCode: 'GenAI-3.2',
    kLevel: 'K2',
    topic: 'データプライバシーとセキュリティリスク',
    question: '生成AIがテスト環境の操作コマンドを提案し、自動実行する仕組みを検討しています。被害範囲を抑える設計として最も適切なものはどれですか。',
    choices: ['管理者権限を常時与えて失敗を減らす', '実行可能な操作と対象を許可リスト化し、重要操作には承認を要求する', 'モデルが自信ありと答えれば検査を省略する', 'すべての環境で同じ秘密情報を共有する'],
    correctAnswerIndex: 1,
    explanation: 'モデルの出力は誤りや攻撃入力の影響を受けるため、実行主体へ必要最小限の権限だけを与えます。許可されたコマンド、対象環境、引数を制限し、破壊的操作や外部送信には人の承認を設けます。監査ログ、秘密情報の分離、停止手段も用意して被害範囲を限定します。',
    reviewerStatus: 'reviewed',
  },
  {
    id: 'ct-genai-018',
    sectionRef: '3.3',
    sourcePolicy: 'original',
    officialQuestionUsed: false,
    certificationReference: 'ISTQB CT-GenAI syllabus v1.1 referenced only as topic map',
    loCode: 'GenAI-3.3',
    kLevel: 'K2',
    topic: 'エネルギー消費と環境影響',
    question: '毎夜、変更のない全テスト資産を大型モデルで再分析しています。環境影響と費用を抑えつつ価値を保つ改善はどれですか。',
    choices: ['回答を長くして一回当たりの処理量を増やす', '同じ要求を複数の大型モデルへ常に送る', '変更箇所を特定し、必要な対象だけを適切な規模のモデルで処理する', '結果を保存せず毎回同じ処理を繰り返す'],
    correctAnswerIndex: 2,
    explanation: '変更のない資産まで毎回処理すると、推論回数とトークン量が増え、電力消費と費用が大きくなります。差分処理、結果の再利用、入力の簡潔化、用途に足りる小さなモデルの選択が有効です。ただし品質への影響を測り、必要な分析範囲を削り過ぎないようにします。',
    reviewerStatus: 'reviewed',
  },
  {
    id: 'ct-genai-019',
    sectionRef: '3.3',
    sourcePolicy: 'original',
    officialQuestionUsed: false,
    certificationReference: 'ISTQB CT-GenAI syllabus v1.1 referenced only as topic map',
    loCode: 'GenAI-3.3',
    kLevel: 'K2',
    topic: 'エネルギー消費と環境影響',
    question: '二つの生成AI利用案の環境影響を比較する際、最も適切な評価方法はどれですか。',
    choices: ['モデル名の印象だけで決める', '一回の応答時間だけを測る', '出力の文字数だけで全影響を判断する', '利用回数、処理量、モデル規模、基盤のエネルギー情報と得られる効果を合わせて評価する'],
    correctAnswerIndex: 3,
    explanation: '環境影響は一回の応答だけでなく、利用頻度、入出力トークン、モデル規模、再試行、基盤設備などに左右されます。可能な範囲で消費量の情報を集め、欠陥検出や工数削減など得られる価値と比較します。不確実な推定値は前提を明示し、継続的に見直すことが重要です。',
    reviewerStatus: 'reviewed',
  },
  {
    id: 'ct-genai-020',
    sectionRef: '3.4',
    sourcePolicy: 'original',
    officialQuestionUsed: false,
    certificationReference: 'ISTQB CT-GenAI syllabus v1.1 referenced only as topic map',
    loCode: 'GenAI-3.4',
    kLevel: 'K1',
    topic: 'AI規制・標準・ベストプラクティスフレームワーク',
    question: '生成AIをテスト業務へ導入する際、規制や組織ルールへの対応を支える記録として最も重要なものはどれですか。',
    choices: ['利用目的、使用データ、モデル、評価結果、承認者の記録', '利用者が感じた便利さだけの記録', '生成された文章の文字数だけの記録', 'モデルへ付けた愛称の一覧'],
    correctAnswerIndex: 0,
    explanation: '利用目的、対象データ、モデルや版、リスク評価、検証結果、承認経路を記録すると、後から判断の妥当性と責任分担を確認できます。適用される法令や社内規則は用途や地域で異なるため、担当部門と確認し、変更時に記録を更新できる管理方法を整えることが重要です。',
    reviewerStatus: 'reviewed',
  },
  {
    id: 'ct-genai-021',
    sectionRef: '3.4',
    sourcePolicy: 'original',
    officialQuestionUsed: false,
    certificationReference: 'ISTQB CT-GenAI syllabus v1.1 referenced only as topic map',
    loCode: 'GenAI-3.4',
    kLevel: 'K1',
    topic: 'AI規制・標準・ベストプラクティスフレームワーク',
    question: 'AIリスク管理のフレームワークをテストチームが利用する主な目的はどれですか。',
    choices: ['すべてのリスクをモデル提供者へ移すため', 'リスクの特定、評価、対応、監視を一貫した手順で行うため', '人によるレビューを不要にするため', 'どの用途でも同じ対策だけを適用するため'],
    correctAnswerIndex: 1,
    explanation: 'リスク管理の枠組みは、用途と影響を把握し、リスクを特定・評価して対策を選び、その有効性を監視する共通手順を与えます。単なる確認表ではなく、関係者、責任、記録、継続改善を結び付けるために使います。具体的な対策は利用場面と影響度に応じて調整します。',
    reviewerStatus: 'reviewed',
  },
  {
    id: 'ct-genai-022',
    sectionRef: '4.1',
    sourcePolicy: 'original',
    officialQuestionUsed: false,
    certificationReference: 'ISTQB CT-GenAI syllabus v1.1 referenced only as topic map',
    loCode: 'GenAI-4.1',
    kLevel: 'K2',
    topic: 'アーキテクチャアプローチ（RAG・LLMエージェント含む）',
    question: '頻繁に更新される社内テスト規約に基づいて質問へ回答させたい場合、RAGを使う主な利点はどれですか。',
    choices: ['モデルの全パラメータを質問のたびに再学習できる', '検索を行わずモデルの記憶だけで回答できる', '関連文書を検索して文脈へ加え、更新情報と根拠を回答に反映しやすい', '取得文書が誤っていても回答が必ず正しくなる'],
    correctAnswerIndex: 2,
    explanation: 'RAGは質問に関連する文書を検索し、その内容をモデルへの文脈として渡します。頻繁に変わる規約を再学習せず更新しやすく、回答に根拠箇所を添えやすい点が利点です。ただし検索漏れ、古い文書、アクセス制御の不備があれば誤答するため、取得品質と出典も検証します。',
    reviewerStatus: 'reviewed',
  },
  {
    id: 'ct-genai-023',
    sectionRef: '4.1',
    sourcePolicy: 'original',
    officialQuestionUsed: false,
    certificationReference: 'ISTQB CT-GenAI syllabus v1.1 referenced only as topic map',
    loCode: 'GenAI-4.1',
    kLevel: 'K2',
    topic: 'アーキテクチャアプローチ（RAG・LLMエージェント含む）',
    question: 'LLMエージェントが障害票を読み、テストを実行し、結果を課題管理へ登録します。この構成で特に重要な制御はどれですか。',
    choices: ['エージェントへ全システムの無制限な権限を与える', '計画と実行を記録し、ツール権限を限定して重要操作に承認点を置く', '失敗時も同じ操作を無制限に繰り返す', '外部ツールの戻り値を検証せず次の操作へ進む'],
    correctAnswerIndex: 1,
    explanation: 'エージェントは複数の判断とツール操作を連続して行うため、一つの誤りが外部システムへ波及します。利用可能なツールと権限、反復回数、費用を制限し、重要操作には承認を設けます。計画、入力、出力、実行結果を記録し、異常時に停止できる仕組みも必要です。',
    reviewerStatus: 'reviewed',
  },
  {
    id: 'ct-genai-024',
    sectionRef: '4.1',
    sourcePolicy: 'original',
    officialQuestionUsed: false,
    certificationReference: 'ISTQB CT-GenAI syllabus v1.1 referenced only as topic map',
    loCode: 'GenAI-4.1',
    kLevel: 'K2',
    topic: 'アーキテクチャアプローチ（RAG・LLMエージェント含む）',
    question: '機密性の高い要求仕様を扱うテスト支援基盤を設計します。クラウド型と組織内配置型を比較する際、最も適切な観点はどれですか。',
    choices: ['モデルの名称だけで選ぶ', '画面の色だけで選ぶ', '利用者数を考慮せず初期費用だけで選ぶ', 'データ管理、性能、運用能力、費用、更新性を用途のリスクと合わせて比較する'],
    correctAnswerIndex: 3,
    explanation: '配置方式には一律の正解はありません。データの保存場所と管理権限、遅延、拡張性、モデル更新、監視、必要な運用人材、総費用を比較します。機密度や法的条件を満たせるかを先に確認し、概念実証で品質と性能を測って、用途ごとに妥当な構成を選択します。',
    reviewerStatus: 'reviewed',
  },
  {
    id: 'ct-genai-025',
    sectionRef: '4.2',
    sourcePolicy: 'original',
    officialQuestionUsed: false,
    certificationReference: 'ISTQB CT-GenAI syllabus v1.1 referenced only as topic map',
    loCode: 'GenAI-4.2',
    kLevel: 'K2',
    topic: 'ファインチューニングとLLMOps',
    question: 'テスト用語と出力形式を安定させるため、ファインチューニングを検討しています。実施前に確認すべきこととして最も適切なものはどれですか。',
    choices: ['プロンプトや検索拡張で目的を満たせるかを比較し、十分な品質の学習データを確保する', '少量の未確認データでも必ず改善すると考える', '更新後の評価は不要とする', '機密データほど広く共有して学習量を増やす'],
    correctAnswerIndex: 0,
    explanation: 'ファインチューニングには学習データの整備、計算資源、版管理、再評価が必要です。まずプロンプト改善やRAGで解決できるかを比較し、目的に合う高品質で利用許諾済みのデータを準備します。学習後は対象能力の改善だけでなく、過学習や他能力の低下、情報漏えいも評価します。',
    reviewerStatus: 'reviewed',
  },
  {
    id: 'ct-genai-026',
    sectionRef: '4.2',
    sourcePolicy: 'original',
    officialQuestionUsed: false,
    certificationReference: 'ISTQB CT-GenAI syllabus v1.1 referenced only as topic map',
    loCode: 'GenAI-4.2',
    kLevel: 'K2',
    topic: 'ファインチューニングとLLMOps',
    question: 'モデル提供側の更新後、同じプロンプトでもテストケース品質が低下しました。LLMOpsの対応として最も適切なものはどれですか。',
    choices: ['利用者の記憶だけで以前との違いを判断する', 'モデル版、プロンプト、評価データを管理し、更新前後の回帰評価を行う', '更新があれば過去の評価結果を削除する', '品質低下を避けるため監視を停止する'],
    correctAnswerIndex: 1,
    explanation: '生成AI基盤では、モデル、プロンプト、検索資料、設定の変更が出力へ影響します。それぞれの版と評価結果を記録し、代表的な評価データで更新前後を比較します。閾値を下回った場合に切り戻しや利用停止ができる手順を持ち、本番での品質や費用も継続監視します。',
    reviewerStatus: 'reviewed',
  },
  {
    id: 'ct-genai-027',
    sectionRef: '4.2',
    sourcePolicy: 'original',
    officialQuestionUsed: false,
    certificationReference: 'ISTQB CT-GenAI syllabus v1.1 referenced only as topic map',
    loCode: 'GenAI-4.2',
    kLevel: 'K2',
    topic: 'ファインチューニングとLLMOps',
    question: '生成AIによる障害分類を運用開始した後、監視対象として最も適切な組合せはどれですか。',
    choices: ['応答文字数と利用者名だけ', 'モデルの公開日だけ', '分類精度、入力分布の変化、遅延、費用、失敗率', 'チームの会議回数だけ'],
    correctAnswerIndex: 2,
    explanation: '運用後は正解率などの品質だけでなく、入力傾向の変化、応答時間、費用、利用量、形式エラー、安全上の失敗も監視します。入力分布が変わると、以前の評価結果が当てはまらなくなる場合があります。警告条件、再評価の時期、担当者、停止基準を事前に定めておきます。',
    reviewerStatus: 'reviewed',
  },
  {
    id: 'ct-genai-028',
    sectionRef: '5.1',
    sourcePolicy: 'original',
    officialQuestionUsed: false,
    certificationReference: 'ISTQB CT-GenAI syllabus v1.1 referenced only as topic map',
    loCode: 'GenAI-5.1',
    kLevel: 'K2',
    topic: '導入のロードマップ',
    question: 'テスト部門が生成AI導入の最初の対象業務を選びます。最も適切な選定方法はどれですか。',
    choices: ['効果、実現性、データ機密度、誤りの影響を評価し、小さく検証できる業務を選ぶ', '最も重大な本番操作から試す', '目的を決めず、利用回数が多い業務を選ぶ', '測定できない業務だけを優先する'],
    correctAnswerIndex: 0,
    explanation: '初期対象は、期待効果が測定でき、必要なデータを安全に扱え、誤りを人が検出・修正できる業務が適しています。基準値と成功条件を定めて小規模に試し、品質、時間、費用、利用者の負担を評価します。結果を基に継続、改善、停止を判断して段階的に範囲を広げます。',
    reviewerStatus: 'reviewed',
  },
  {
    id: 'ct-genai-029',
    sectionRef: '5.1',
    sourcePolicy: 'original',
    officialQuestionUsed: false,
    certificationReference: 'ISTQB CT-GenAI syllabus v1.1 referenced only as topic map',
    loCode: 'GenAI-5.1',
    kLevel: 'K2',
    topic: '導入のロードマップ',
    question: '概念実証でテスト設計時間が短縮されましたが、誤った期待結果も増えました。次の判断として最も適切なものはどれですか。',
    choices: ['時間短縮だけを理由に全社展開する', '誤りを隠して利用者数を増やす', '導入を永久に禁止し、原因分析を行わない', '便益と誤りの影響を評価し、レビューや用途制限を加えた再試行条件を定める'],
    correctAnswerIndex: 3,
    explanation: '一つの指標だけで導入可否を決めるべきではありません。短縮時間と、誤りの検出・修正に要する工数、見逃した場合の影響を合わせて評価します。プロンプト改善、対象範囲の限定、レビュー強化などの対策を設け、受入基準を満たすか再試行して次の段階を判断します。',
    reviewerStatus: 'reviewed',
  },
  {
    id: 'ct-genai-030',
    sectionRef: '5.2',
    sourcePolicy: 'original',
    officialQuestionUsed: false,
    certificationReference: 'ISTQB CT-GenAI syllabus v1.1 referenced only as topic map',
    loCode: 'GenAI-5.2',
    kLevel: 'K2',
    topic: '変革のマネジメント',
    question: '生成AI導入に対し、テスターから役割喪失や品質低下への不安が出ています。変革を進める対応として最も適切なものはどれですか。',
    choices: ['目的と役割の変化を説明し、利用者を試行・評価・ルール作りへ参加させる', '懸念を無視して利用を義務化する', '経営層だけで手順を決め、現場へ結果のみ伝える', '失敗事例を共有せず成功例だけを示す'],
    correctAnswerIndex: 0,
    explanation: '変革には技術導入だけでなく、役割、技能、手順、評価方法の見直しが伴います。目的と判断責任が人に残る範囲を明確にし、現場を試行やルール作りへ参加させます。教育、相談窓口、率直な失敗共有、利用状況の測定を通じて懸念を扱い、段階的に定着させます。',
    reviewerStatus: 'reviewed',
  },
];
